DROP DATABASE IF EXISTS sync_app;
DROP DATABASE IF EXISTS railway;
CREATE DATABASE railway;
USE railway;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS noteAttachments;
DROP TABLE IF EXISTS books;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(60) NOT NULL,
  password VARCHAR(20) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users VALUES(1, "raghu@gmail.com", "Raghu", "Password@123", utc_timestamp());
INSERT INTO users VALUES(2, "jogn@gmail.com", "John", "Password@321", utc_timestamp());


CREATE TABLE notes (
  id VARCHAR(60) PRIMARY KEY NOT NULL,
  userId INT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  thumbnail VARCHAR(255),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE noteAttachments (
   id VARCHAR(60) PRIMARY KEY NOT NULL,
  noteId VARCHAR(60) NOT NULL,
  caption VARCHAR(255),
  fileName VARCHAR(255),
  FOREIGN KEY (noteId) REFERENCES notes(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE books (
	id VARCHAR(60) PRIMARY KEY NOT NULL,
  userId INT NOT NULL,
  title VARCHAR(255) NOT NULL UNIQUE,
  author VARCHAR(255) NOT NULL,
  content TEXT,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

